### ISSUE TITLE
Web Extension Tools interaction with Interledger Pay

### ISSUE THREAD

**Issue by Tymmmy** [interledger/interledger-pay#31]
## Context
We will use Interledger Pay to finalize payments from Web Extension Tool.
For this we need to make sure the recipient reveived is prepopulated.

## Todos
- [x] Have the Interledger Pay ready to receive receiver WA in url param as well - receiver WA is in the tools config
- [x] Prepopulate with the receiver WA the new page
- [x] Add predefined tiping/support values - 1$ - 5$ - 10$ - custom value
- [x] Add note input
- [x] Have Pay with interledger button - then the same functionality - Quote and the rest
- [ ] Test everything is ok

**Comment by lengyel-arpad85** [comment]
additionally discuss, further 2 parameters
- amount
- note

for cases when we have predefined amounts in widget and/or input in widget for the users
